#!/usr/bin/env swift
//
// Dev-time generator. Parses the OS tz database and emits
// Sources/ZoneBarCore/Generated/TimeZoneCountry.swift
//
// Usage (from the repo root):
//     swift Scripts/generate_tz_table.swift
//
// zone.tab lines look like:   SE	+5920+01803	Europe/Stockholm
// iso3166.tab lines like:     SE	Sweden
//
import Foundation

let zoneTab = "/usr/share/zoneinfo/zone.tab"
let isoTab = "/usr/share/zoneinfo/iso3166.tab"
let outputPath = "Sources/ZoneBarCore/Generated/TimeZoneCountry.swift"

func readLines(_ path: String) -> [String] {
    guard let text = try? String(contentsOfFile: path, encoding: .utf8) else {
        FileHandle.standardError.write("error: cannot read \(path)\n".data(using: .utf8)!)
        exit(1)
    }
    return text.split(separator: "\n", omittingEmptySubsequences: true)
        .map(String.init)
        .filter { !$0.hasPrefix("#") && !$0.trimmingCharacters(in: .whitespaces).isEmpty }
}

// zone identifier -> ISO 3166 alpha-2 country code
var zoneToCountry: [String: String] = [:]
for line in readLines(zoneTab) {
    let fields = line.split(separator: "\t", omittingEmptySubsequences: false).map(String.init)
    guard fields.count >= 3 else { continue }
    let code = fields[0].trimmingCharacters(in: .whitespaces)
    let zone = fields[2].trimmingCharacters(in: .whitespaces)
    guard code.count == 2, !zone.isEmpty else { continue }
    zoneToCountry[zone] = code
}

// ISO 3166 alpha-2 country code -> English country name
var countryNames: [String: String] = [:]
for line in readLines(isoTab) {
    let fields = line.split(separator: "\t", omittingEmptySubsequences: false).map(String.init)
    guard fields.count >= 2 else { continue }
    let code = fields[0].trimmingCharacters(in: .whitespaces)
    let name = fields[1].trimmingCharacters(in: .whitespaces)
    guard code.count == 2, !name.isEmpty else { continue }
    countryNames[code] = name
}

guard !zoneToCountry.isEmpty, !countryNames.isEmpty else {
    FileHandle.standardError.write("error: parsed no rows\n".data(using: .utf8)!)
    exit(1)
}

func swiftLiteral(_ dict: [String: String], name: String, doc: String) -> String {
    var out = "/// \(doc)\npublic let \(name): [String: String] = [\n"
    for key in dict.keys.sorted() {
        out += "    \(String(reflecting: key)): \(String(reflecting: dict[key]!)),\n"
    }
    out += "]\n"
    return out
}

let header = """
// Generated by Scripts/generate_tz_table.swift — do not edit by hand.
// Source: /usr/share/zoneinfo/zone.tab and /usr/share/zoneinfo/iso3166.tab
// Regenerate with: swift Scripts/generate_tz_table.swift

"""

let body =
    header + "\n"
    + swiftLiteral(
        zoneToCountry, name: "tzIdentifierToCountryCode",
        doc: "Maps an IANA time zone identifier to its ISO 3166 alpha-2 country code.")
    + "\n"
    + swiftLiteral(
        countryNames, name: "countryCodeToName",
        doc: "Maps an ISO 3166 alpha-2 country code to its English name.")

let outputURL = URL(fileURLWithPath: outputPath)
try? FileManager.default.createDirectory(
    at: outputURL.deletingLastPathComponent(), withIntermediateDirectories: true)
try body.write(to: outputURL, atomically: true, encoding: .utf8)

print("wrote \(outputPath): \(zoneToCountry.count) zones, \(countryNames.count) countries")
